### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by RiPPERD** [renato-roca-dev/calorius#1]
Hello not an issue but i am english and couldnt find much online. i appriciate your time on this so i have made an english version using your code and am sharing it here for you

HTML
`<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="renato-roca-dev">
    <link rel="stylesheet" href="style.css">
    <link rel="shortcut icon" type="imagem/x-icon" href="img/title_icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <title>Calorie Calculator</title>
</head>
<body>
    <div class="container">
        <main class="main__content">
            <header>
                <h1>Calorie Calculator</h1>
            </header>
            <form id="form" onsubmit="return false">
                <div class="form__group">
                    <label for="weight">Current Weight:</label>
                    <input type="number" id="weight" placeholder="Ex: 72,5" step="0.01" required min="20" max="300" >
                    <p>kg</p>
                </div>
                <div class="form__group">
                    <label for="height">Height:</label>
                    <input type="number" id="height" placeholder="Ex: 160" step="0.01" required min="1" max="240"> 
                    <p>cm</p>
                </div>
                <div class="form__group">
                    <label for="age">Age:</label>
                    <input type="number" id="age" placeholder="Ex: 25" step="1" required min="1" max="120">
                    <p>Years Old</p>
                </div>
                <div class="form__group">
                    <label for="gender">Sex:</label>
                    <select id="gender" required>
                        <option value="" selected></option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                  </div>
                <div class="form__group">
                    <label for="activity__level">Physical Activity Level:</label>
                    <select id="activity__level" required >
                        <option value="" selected></option>
                        <option value="1.2">Sedentary</option>
                        <option value="1.375">Little Activity</option>
                        <option value="1.55">Moderate Activity</option>
                        <option value="1.725">Intense Activity</option>
                        <option value="1.9">Very Intense Activity</option>
                    </select>
                </div>
                <div class="form__group">
                    <button type="submit" id="result__button"  >Calculate!</button>
                </div>
                <div class="result__content" >
                    <ul>
                        <li>
                         <p id="outBasal"></p>
                        </li>
                        <li>
                         <p id="outMaintenance"></p>
                        </li>
                        <li>
                         <p id="outGainWeight"></p>
                        </li>
                        <li>
                         <p id="outLoseWeight"></p>
                        </li>
                    </ul>
                </div>
            </form>
        </main>
    <script src="script.js" type="text/javascript"></script>
</body>
</html>`

JAVASCRIPT FILE

`const form = document.getElementById('form');
form.addEventListener('submit', handleSubmit);

function handleSubmit(event) {
  event.preventDefault();

  const weight = getInputNumberValue("weight");
  const height = getInputNumberValue("height");
  const age = getInputNumberValue("age");
  const gender = getSelectedValue("gender");
  const activityLevel = getSelectedValue("activity__level");

  const basal = Math.round(
    gender === 'female'
      ? (655 + (9.6 * weight) + (1.8 * height) - (4.7 * age))
      : (66 + (13.7 * weight) + (5 * height) - (6.8 * age))
  );

  const maintenance = Math.round(basal * Number(activityLevel));
  const gainWeight = maintenance + 450;
  const loseWeight = maintenance - 450;

  document.getElementById("outBasal");
  outBasal.innerHTML = "Your basal metabolism is " + basal  + " calories";;

  document.getElementById("outMaintenance");
  outMaintenance.innerHTML = "To maintain weight you need to consume on average " + maintenance + " calories" ;

  document.getElementById("outLoseweight");
  outLoseWeight.innerHTML = "To lose weight you need to consume on average " + loseWeight + " calories" ;

  document.getElementById("outGainWeight");
  outGainWeight.innerHTML = "To gain weight you need to consume on average " + gainWeight + " calories" ;
}

function getSelectedValue(id) {
  const select = document.getElementById(id);
  return select.options[select.selectedIndex].value;
}

function getInputNumberValue(id) {
  return Number(document.getElementById(id).value);
}
`

**Comment by renato-roca-dev** [comment]
Sup! I appreciate for your time on passing my code to english and to share with me! Seems very good to me. 

Take care!
